package com.kuangkee.search.pojo;

import java.util.Date;

public class ArticleDesc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article_desc.article_id
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    private Integer articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article_desc.create_time
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article_desc.update_time
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article_desc.content
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article_desc.article_id
     *
     * @return the value of tb_article_desc.article_id
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article_desc.article_id
     *
     * @param articleId the value for tb_article_desc.article_id
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article_desc.create_time
     *
     * @return the value of tb_article_desc.create_time
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article_desc.create_time
     *
     * @param createTime the value for tb_article_desc.create_time
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article_desc.update_time
     *
     * @return the value of tb_article_desc.update_time
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article_desc.update_time
     *
     * @param updateTime the value for tb_article_desc.update_time
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article_desc.content
     *
     * @return the value of tb_article_desc.content
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article_desc.content
     *
     * @param content the value for tb_article_desc.content
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}