package com.kuangkee.search.pojo;

import java.util.Date;

public class Brand {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_brand.brand_id
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    private Integer brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_brand.brand_name
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_brand.order_weight
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    private String orderWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_brand.creater
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_brand.is_show
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    private String isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_brand.create_time
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_brand.update_time
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_brand.brand_id
     *
     * @return the value of tb_brand.brand_id
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_brand.brand_id
     *
     * @param brandId the value for tb_brand.brand_id
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_brand.brand_name
     *
     * @return the value of tb_brand.brand_name
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_brand.brand_name
     *
     * @param brandName the value for tb_brand.brand_name
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_brand.order_weight
     *
     * @return the value of tb_brand.order_weight
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    public String getOrderWeight() {
        return orderWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_brand.order_weight
     *
     * @param orderWeight the value for tb_brand.order_weight
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    public void setOrderWeight(String orderWeight) {
        this.orderWeight = orderWeight == null ? null : orderWeight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_brand.creater
     *
     * @return the value of tb_brand.creater
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_brand.creater
     *
     * @param creater the value for tb_brand.creater
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_brand.is_show
     *
     * @return the value of tb_brand.is_show
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    public String getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_brand.is_show
     *
     * @param isShow the value for tb_brand.is_show
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    public void setIsShow(String isShow) {
        this.isShow = isShow == null ? null : isShow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_brand.create_time
     *
     * @return the value of tb_brand.create_time
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_brand.create_time
     *
     * @param createTime the value for tb_brand.create_time
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_brand.update_time
     *
     * @return the value of tb_brand.update_time
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_brand.update_time
     *
     * @param updateTime the value for tb_brand.update_time
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}