package com.kuangkee.search.mapper;

import com.kuangkee.search.pojo.ArticleDesc;
import com.kuangkee.search.pojo.ArticleDescExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleDescMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_desc
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    int countByExample(ArticleDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_desc
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    int deleteByExample(ArticleDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_desc
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    int insert(ArticleDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_desc
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    int insertSelective(ArticleDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_desc
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    List<ArticleDesc> selectByExampleWithBLOBs(ArticleDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_desc
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    List<ArticleDesc> selectByExample(ArticleDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_desc
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") ArticleDesc record, @Param("example") ArticleDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_desc
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") ArticleDesc record, @Param("example") ArticleDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_desc
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    int updateByExample(@Param("record") ArticleDesc record, @Param("example") ArticleDescExample example);
}