package com.kuangkee.search.mapper;

import com.kuangkee.search.pojo.UserSearchLog;
import com.kuangkee.search.pojo.UserSearchLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserSearchLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_search_log
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    int countByExample(UserSearchLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_search_log
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    int deleteByExample(UserSearchLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_search_log
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    int deleteByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_search_log
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    int insert(UserSearchLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_search_log
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    int insertSelective(UserSearchLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_search_log
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    List<UserSearchLog> selectByExample(UserSearchLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_search_log
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    UserSearchLog selectByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_search_log
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserSearchLog record, @Param("example") UserSearchLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_search_log
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    int updateByExample(@Param("record") UserSearchLog record, @Param("example") UserSearchLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_search_log
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    int updateByPrimaryKeySelective(UserSearchLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_search_log
     *
     * @mbggenerated Sat Jan 06 16:55:39 CST 2018
     */
    int updateByPrimaryKey(UserSearchLog record);
}